/**
 * Ticket API
 * Ticket API for illustrating purpose.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlguenego@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Response from './model/Response';
import Ticket from './model/Ticket';
import AllTicketsApi from './api/AllTicketsApi';
import OneTicketApi from './api/OneTicketApi';


/**
* Ticket_API_for_illustrating_purpose_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var TicketApi = require('index'); // See note below*.
* var xxxSvc = new TicketApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new TicketApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new TicketApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new TicketApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Response model constructor.
     * @property {module:model/Response}
     */
    Response,

    /**
     * The Ticket model constructor.
     * @property {module:model/Ticket}
     */
    Ticket,

    /**
    * The AllTicketsApi service constructor.
    * @property {module:api/AllTicketsApi}
    */
    AllTicketsApi,

    /**
    * The OneTicketApi service constructor.
    * @property {module:api/OneTicketApi}
    */
    OneTicketApi
};
