<definitions>
    <types>
        <schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/">
            <element name="JLGSplitterRequest">
                <complexType>
                    <sequence>
                        <element minOccurs="1" maxOccurs="1" name="message" type="string"/>
                        <element minOccurs="1" maxOccurs="1" name="splitter" type="string"/>
                    </sequence>
                </complexType>
            </element>
            <element name="JLGSplitterResponse">
                <complexType>
                    <sequence>
                        <element minOccurs="1" maxOccurs="unbounded" name="result" type="string"/>
                    </sequence>
                </complexType>
            </element>
        </schema>
    </types>
    <message name="JLGSplitterSoapIn">
        <part name="parameters" element="JLGSplitterRequest"/>
    </message>
    <message name="JLGSplitterSoapOut">
        <part name="parameters" element="JLGSplitterResponse"/>
    </message>
    <portType name="JLGSplitterSoapPort">
        <!-- The operation name must be the same as the one specified in the service object -->
        <operation name="JLGSplitter">
            <input message="JLGSplitterSoapIn"/>
            <output message="JLGSplitterSoapOut"/>
        </operation>
    </portType>
    <binding name="JLGSplitterServiceSoapBinding" type="JLGSplitterSoapPort">
        <binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="JLGSplitter">
            <operation soapAction="JLGSplitter" style="document"/>
            <input>
                <body use="literal"/>
            </input>
            <output>
                <body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="JLGSplitterService">
        <port name="JLGSplitterServiceSoapPort" binding="JLGSplitterServiceSoapBinding">
            <address location="http://localhost:8000/wsdl"/>
        </port>
    </service>
</definitions>