<definitions targetNamespace="http://tempuri.org/" 
    xmlns:s="http://www.w3.org/2001/XMLSchema" 
    xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
    xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" 
    xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" 
    xmlns:tns="http://tempuri.org/" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" 
     
    >
    <!-- WSDL TYPES: definition of the data types that are used in the web service -->
    <types>
        <s:schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/">
            <s:element name="MessageSplitterRequest">
                <s:complexType>
                    <s:sequence>
                        <s:element minOccurs="1" maxOccurs="1" name="message" type="s:string"/>
                        <s:element minOccurs="1" maxOccurs="1" name="splitter" type="s:string"/>
                    </s:sequence>
                </s:complexType>
            </s:element>
            <s:element name="MessageSplitterResponse">
                <s:complexType>
                    <s:sequence>
                        <s:element minOccurs="1" maxOccurs="unbounded" name="result" type="s:string"/>
                    </s:sequence>
                </s:complexType>
            </s:element>
        </s:schema>
    </types>
    <!-- MESSAGES: defines the data being exchanged between the service and client -->
    <message name="MessageSplitterSoapIn">
        <part name="parameters" element="tns:MessageSplitterRequest"/>
    </message>
    <message name="MessageSplitterSoapOut">
        <part name="parameters" element="tns:MessageSplitterResponse"/>
    </message>
    <!-- PORT TYPES: defines the complete communication operation (one way/round trip) -->
    <portType name="MessageSplitterSoapPort">
        <!-- The operation name must be the same as the one specified in the service object -->
        <operation name="MessageSplitter">
            <input message="tns:MessageSplitterSoapIn"/>
            <output message="tns:MessageSplitterSoapOut"/>
        </operation>
    </portType>
    <!-- BINDING: provides details on how a portType operation will actually be transmitted -->
    <binding name="MessageSplitterServiceSoapBinding" type="tns:MessageSplitterSoapPort">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="MessageSplitter">
            <soap:operation soapAction="MessageSplitter" style="document"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <binding name="MessageSplitterServiceSoap12Binding" type="tns:MessageSplitterSoapPort">
        <soap12:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="MessageSplitter">
            <soap12:operation soapAction="MessageSplitter" style="document"/>
            <input>
                <soap12:body use="literal"/>
            </input>
            <output>
                <soap12:body use="literal"/>
            </output>
        </operation>
    </binding>
    <!-- SERVICE:  -->
    <service name="MessageSplitterService">
        <port name="MessageSplitterServiceSoapPort" binding="tns:MessageSplitterServiceSoapBinding">
            <soap:address location="http://localhost:8000/wsdl"/>
        </port>
        <port name="MessageSplitterServiceSoap12Port" binding="tns:MessageSplitterServiceSoap12Binding">
            <soap12:address location="http://localhost:8000/wsdl"/>
        </port>
    </service>
</definitions>