swagger: '2.0'
info:
  description: Ticket API for illustrating purpose.
  version: 1.0.0
  title: Ticket API
  # put the contact info for your development or API team
  contact:
    email: jlguenego@gmail.com

  license:
    name: ISC
    url: https://opensource.org/licenses/ISC

# tags are used for organizing operations
tags:
- name: all-tickets
  description: Operations on all tickets
- name: one-ticket
  description: Operations on one ticket

paths:
  /tickets:
    get:
      tags:
      - all-tickets
      summary: List all tickets
      operationId: retrieveAllTickets
      description: |
        To be able
        to retrieve all tickets.
      produces:
      - application/json
      - application/xml
      parameters: []
      # no paramters.
      responses:
        200:
          description: |
            An object with content pointing on the
            list of all the tickets.
          schema:
            type: object
            items:
              $ref: '#/definitions/Response'
        400:
          description: bad input parameter
    post:
      tags:
      - one-ticket
      summary: Create an new ticket
      operationId: createTicket
      description: |
        Create an new ticket
        on multinline...
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - in: body
        name: ticket
        description: a ticket
        schema:
          $ref: '#/definitions/Ticket'
      responses:
        201:
          description: item created
          schema:
            type: object
            items:
              $ref: '#/definitions/Response'
        400:
          description: invalid input, object invalid
        406:
          description: format not accepted (only JSON and XML)
        409:
          description: "conflict: an existing item already exists"
    delete:
      tags:
      - all-tickets
      summary: Delete all tickets
      operationId: deleteAllTickets
      description: |
        To be able
        to delete all tickets.
      produces:
      - application/json
      - application/xml
      parameters: []
      # no paramters.
      responses:
        204:
          description: |
            No content returned.
        500:
          description: server internal error
  /tickets/{id}:
    get:
      tags:
      - one-ticket
      summary: Retrieve a single ticket
      operationId: retrieveTicket
      description: Retrieve a ticket
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: ticket id
        required: true
        type: string
      responses:
        200:
          description: item retrieved.
          schema:
            type: object
            items:
              $ref: '#/definitions/Response'
        400:
          description: invalid input, object invalid.
        404:
          description: ticket not found.
        406:
          description: format not accepted (only JSON and XML).
    put:
      tags:
      - one-ticket
      summary: Update an new ticket
      operationId: updateTicket
      description: Update a ticket
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: ticket id
        required: true
        type: string
      - name: ticket
        in: body
        description: a ticket
        schema:
          $ref: '#/definitions/Ticket'
      responses:
        200:
          description: item updated.
          schema:
            type: object
            items:
              $ref: '#/definitions/Response'
        400:
          description: invalid input, object invalid.
        404:
          description: ticket not found.
        406:
          description: format not accepted (only JSON and XML).
    delete:
      tags:
      - one-ticket
      summary: Delete an existing ticket.
      operationId: deleteTicket
      description: Delete an existing ticket.
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: ticket id
        required: true
        type: string
      responses:
        200:
          description: item deleted.
          schema:
            type: object
            items:
              $ref: '#/definitions/Response'
        400:
          description: invalid input, object invalid.
        404:
          description: ticket not found.
        406:
          description: format not accepted (only JSON and XML).
definitions:
  Ticket:
    type: object
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      name:
        type: string
        example: Widget Adapter
  Response:
    type: object
    properties:
      content:
        type: object
      error:
        type: object
        
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /example-boa/ticket/1.0.0
schemes:
 - https