kind: Service
apiVersion: v1
metadata:
  #Service name
  name: hello-service
spec:
  selector:
    app: example-boa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
